name: Build and Push to ECR

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main  # Change to your deployment branch

jobs:
  build-and-push:
    name: Build & Push Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

     
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
         aws-access-key-id: ${{ secrets.ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.SECRET_KEY }}
         aws-region: eu-north-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image appointment-service
        run: |
          docker build -t hello-world ./app
          docker tag hello-world:latest 575108922676.dkr.ecr.us-west-1.amazonaws.com/hello-world:latest
          
          
      - name: Push Docker image to ECR
        run: |
          docker push 575108922676.dkr.ecr.us-west-1.amazonaws.com//hello-world:latest
