name: Build and Push to ECR

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main  # Change to your deployment branch
env:
  AWS_REGION: "us-west-1"
permissions:
  id-token: write  
jobs:
  build-and-push:
    name: Build & Push Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

     
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v3
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ env.AWS_REGION }}
      - name: Set up AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
         role-to-assume: arn:aws:iam::575108922676:role/terraform-project-lambda_repo_role # Ensure this matches the role ARN
         role-session-name: github-actions-session

    

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image appointment-service
        run: |
          docker build -t hello-world ./app
          docker tag hello-world:latest 575108922676.dkr.ecr.us-west-1.amazonaws.com/hello-world:latest
          
          
      - name: Push Docker image to ECR
        run: |
          docker push 575108922676.dkr.ecr.us-west-1.amazonaws.com/hello-world:latest
